// Code generated by scripts/gen_abi_constants.go; DO NOT EDIT.
export const TYPE_KIND_I8 = 0;
export const TYPE_KIND_I16 = 1;
export const TYPE_KIND_I32 = 2;
export const TYPE_KIND_I64 = 3;
export const TYPE_KIND_I128 = 4;
export const TYPE_KIND_I256 = 5;
export const TYPE_KIND_U8 = 6;
export const TYPE_KIND_U16 = 7;
export const TYPE_KIND_U32 = 8;
export const TYPE_KIND_U64 = 9;
export const TYPE_KIND_U128 = 10;
export const TYPE_KIND_U256 = 11;
export const TYPE_KIND_F32 = 12;
export const TYPE_KIND_F64 = 13;
export const TYPE_KIND_F128 = 14;
export const TYPE_KIND_F256 = 15;
export const TYPE_KIND_STRING = 16;
export const TYPE_KIND_BYTE = 17;
export const TYPE_KIND_CHAR = 18;
export const TYPE_KIND_BOOL = 19;
export const TYPE_KIND_POINTER = 20;
export const TYPE_KIND_STRUCT = 21;
export const TYPE_KIND_ARRAY = 22;
export const TYPE_KIND_SLICE = 23;
export const TYPE_KIND_MAP = 24;
export const TYPE_KIND_FUNCTION = 25;
export const TYPE_KIND_INTERFACE = 26;

// WASM type descriptor layout (packed u32 fields).
export const TYPE_DESC_KIND_OFFSET = 0;
export const TYPE_DESC_SIZE_OFFSET = 4;
export const TYPE_DESC_INFO1_OFFSET = 8;
export const TYPE_DESC_INFO2_OFFSET = 12;
export const TYPE_DESC_SIZE = 16;
export const FIELD_INFO_OFFSET_OFFSET = 0;
export const FIELD_INFO_TYPE_OFFSET = 4;
export const FIELD_INFO_SIZE = 8;

// WASM runtime layout constants.
export const ARRAY_DATA_OFFSET = 0;
export const ARRAY_LEN_OFFSET = 4;
export const ARRAY_CAP_OFFSET = 8;
export const ARRAY_ELEM_SIZE_OFFSET = 12;
export const ARRAY_ELEM_TYPE_OFFSET = 16;
export const ARRAY_HEADER_SIZE = 20;
export const SLICE_DATA_OFFSET = 0;
export const SLICE_LEN_OFFSET = 4;
export const SLICE_CAP_OFFSET = 8;
export const SLICE_ELEM_SIZE_OFFSET = 12;
export const SLICE_ELEM_TYPE_OFFSET = 16;
export const SLICE_HEADER_SIZE = 20;
export const INTERFACE_DATA_OFFSET = 0;
export const INTERFACE_EXTRA_OFFSET = 4;
export const INTERFACE_SIZE = 8;
export const UNION_TAG_SIZE = 4;
export const UNION_PTR_OFFSET = 4;
export const MAP_HANDLE_SIZE = 8;

// Hash constants.
export const MAP_HASH_SEED = 2538058380;
export const FNV_OFFSET_BASIS = 2166136261;
export const FNV_PRIME = 16777619;

// Big integer/float specs.
export const BIG_INT_WIDTHS = [
  128,
  256,
] as const;
export type BigIntWidth = (typeof BIG_INT_WIDTHS)[number];
export const BIG_FLOAT_SPECS = [
  { bits: 128, words: 2, fracBits: 112n, expBits: 15n, expBias: 16383, decimalDig: 36 },
  { bits: 256, words: 4, fracBits: 236n, expBits: 19n, expBias: 262143, decimalDig: 73 },
] as const;
export type BigFloatSpec = (typeof BIG_FLOAT_SPECS)[number];
export const SOFT_EXTRA_BITS = 3n;

// Core WASM import names.
export const WASM_IMPORT_FERRET_ALLOC = "ferret_alloc";
export const WASM_IMPORT_FERRET_MEMCPY = "ferret_memcpy";
export const WASM_IMPORT_FERRET_ARRAY_GET = "ferret_array_get";
export const WASM_IMPORT_FERRET_ARRAY_NEW = "ferret_array_new";
export const WASM_IMPORT_FERRET_ARRAY_APPEND = "ferret_array_append";
export const WASM_IMPORT_FERRET_ARRAY_SET = "ferret_array_set";
export const WASM_IMPORT_FERRET_MAP_GET = "ferret_map_get";
export const WASM_IMPORT_FERRET_MAP_GET_OPTIONAL_OUT = "ferret_map_get_optional_out";
export const WASM_IMPORT_FERRET_MAP_SET = "ferret_map_set";
export const WASM_IMPORT_FERRET_GLOBAL_PANIC = "ferret_global_panic";
export const WASM_IMPORT_FERRET_POW = "ferret_pow";
export const WASM_IMPORT_FERRET_OPTIONAL_UNWRAP_OR = "ferret_optional_unwrap_or";

export const WASM_CORE_IMPORTS = [
  WASM_IMPORT_FERRET_ALLOC,
  WASM_IMPORT_FERRET_MEMCPY,
  WASM_IMPORT_FERRET_ARRAY_GET,
  WASM_IMPORT_FERRET_ARRAY_NEW,
  WASM_IMPORT_FERRET_ARRAY_APPEND,
  WASM_IMPORT_FERRET_ARRAY_SET,
  WASM_IMPORT_FERRET_MAP_GET,
  WASM_IMPORT_FERRET_MAP_GET_OPTIONAL_OUT,
  WASM_IMPORT_FERRET_MAP_SET,
  WASM_IMPORT_FERRET_GLOBAL_PANIC,
  WASM_IMPORT_FERRET_POW,
  WASM_IMPORT_FERRET_OPTIONAL_UNWRAP_OR,
] as const;
export type WasmCoreImportName = (typeof WASM_CORE_IMPORTS)[number];

export const MAP_KEY_KINDS = [
  "i32",
  "i64",
  "f32",
  "f64",
  "str",
  "bytes",
  "numeric",
  "universal",
] as const;
export type FerretMapKeyKind = (typeof MAP_KEY_KINDS)[number];
